### PR TITLE
Testing a different markdown cell.

### PR DESCRIPTION
**Pull request by julesfowler**
Just testing if redoing a few of the cells looks like I expect before I go whole hog.

### CODE REVIEW

**Comment by ivastar** [comment]
are you also testing how it looks on the rendered pages e.g., https://ivastar.github.io/python-novice-astro/?

**Comment by julesfowler** [comment]
Yup! I figured out how to fix the cell output stuff, but it looks like the references aren't quite linking the way they're supposed to.

**Comment by julesfowler** [comment]
@ivastar Are the section like this intentionally greyed out/inset for emphasis? 
Screen Shot 2019-08-12 at 2 45 51 PM

**Comment by julesfowler** [comment]
@ivastar Like you mentioned via slack -- these were based on not the actual lessons but just the GitHub preview. I'm closing this.

**Pull request closed without merging**
